/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const FirmId = IDL.Text;
export const FinancialData = IDL.Record({
  'revenue' : IDL.Float64,
  'expenses' : IDL.Float64,
  'year' : IDL.Nat,
  'profit' : IDL.Float64,
});
export const FirmInput = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'address' : IDL.Text,
  'contactEmail' : IDL.Text,
  'services' : IDL.Vec(IDL.Text),
  'contactPhone' : IDL.Text,
});
export const FirmProfile = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'address' : IDL.Text,
  'contactEmail' : IDL.Text,
  'services' : IDL.Vec(IDL.Text),
  'contactPhone' : IDL.Text,
});
export const TeamMember = IDL.Record({
  'bio' : IDL.Text,
  'name' : IDL.Text,
  'position' : IDL.Text,
});
export const TeamMemberInput = IDL.Record({
  'bio' : IDL.Text,
  'name' : IDL.Text,
  'position' : IDL.Text,
});

export const idlService = IDL.Service({
  'addFinancialData' : IDL.Func([FirmId, FinancialData], [], []),
  'addFirm' : IDL.Func([FirmId, FirmInput], [], []),
  'getAllFirms' : IDL.Func([], [IDL.Vec(FirmProfile)], ['query']),
  'getFinancialData' : IDL.Func(
      [FirmId],
      [IDL.Opt(IDL.Vec(FinancialData))],
      ['query'],
    ),
  'getFirmProfile' : IDL.Func([FirmId], [IDL.Opt(FirmProfile)], ['query']),
  'getTeamMembers' : IDL.Func(
      [FirmId],
      [IDL.Opt(IDL.Vec(TeamMember))],
      ['query'],
    ),
  'updateTeamMembers' : IDL.Func([FirmId, IDL.Vec(TeamMemberInput)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const FirmId = IDL.Text;
  const FinancialData = IDL.Record({
    'revenue' : IDL.Float64,
    'expenses' : IDL.Float64,
    'year' : IDL.Nat,
    'profit' : IDL.Float64,
  });
  const FirmInput = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'address' : IDL.Text,
    'contactEmail' : IDL.Text,
    'services' : IDL.Vec(IDL.Text),
    'contactPhone' : IDL.Text,
  });
  const FirmProfile = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'address' : IDL.Text,
    'contactEmail' : IDL.Text,
    'services' : IDL.Vec(IDL.Text),
    'contactPhone' : IDL.Text,
  });
  const TeamMember = IDL.Record({
    'bio' : IDL.Text,
    'name' : IDL.Text,
    'position' : IDL.Text,
  });
  const TeamMemberInput = IDL.Record({
    'bio' : IDL.Text,
    'name' : IDL.Text,
    'position' : IDL.Text,
  });
  
  return IDL.Service({
    'addFinancialData' : IDL.Func([FirmId, FinancialData], [], []),
    'addFirm' : IDL.Func([FirmId, FirmInput], [], []),
    'getAllFirms' : IDL.Func([], [IDL.Vec(FirmProfile)], ['query']),
    'getFinancialData' : IDL.Func(
        [FirmId],
        [IDL.Opt(IDL.Vec(FinancialData))],
        ['query'],
      ),
    'getFirmProfile' : IDL.Func([FirmId], [IDL.Opt(FirmProfile)], ['query']),
    'getTeamMembers' : IDL.Func(
        [FirmId],
        [IDL.Opt(IDL.Vec(TeamMember))],
        ['query'],
      ),
    'updateTeamMembers' : IDL.Func([FirmId, IDL.Vec(TeamMemberInput)], [], []),
  });
};

export const init = ({ IDL }) => { return []; };