/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface FinancialData {
  'revenue' : number,
  'expenses' : number,
  'year' : bigint,
  'profit' : number,
}
export type FirmId = string;
export interface FirmInput {
  'name' : string,
  'description' : string,
  'address' : string,
  'contactEmail' : string,
  'services' : Array<string>,
  'contactPhone' : string,
}
export interface FirmProfile {
  'name' : string,
  'description' : string,
  'address' : string,
  'contactEmail' : string,
  'services' : Array<string>,
  'contactPhone' : string,
}
export interface TeamMember {
  'bio' : string,
  'name' : string,
  'position' : string,
}
export interface TeamMemberInput {
  'bio' : string,
  'name' : string,
  'position' : string,
}
export interface _SERVICE {
  'addFinancialData' : ActorMethod<[FirmId, FinancialData], undefined>,
  'addFirm' : ActorMethod<[FirmId, FirmInput], undefined>,
  'getAllFirms' : ActorMethod<[], Array<FirmProfile>>,
  'getFinancialData' : ActorMethod<[FirmId], [] | [Array<FinancialData>]>,
  'getFirmProfile' : ActorMethod<[FirmId], [] | [FirmProfile]>,
  'getTeamMembers' : ActorMethod<[FirmId], [] | [Array<TeamMember>]>,
  'updateTeamMembers' : ActorMethod<
    [FirmId, Array<TeamMemberInput>],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];